version: '3.7'

services:
    php:
        restart: unless-stopped
        ports:
            - 80:8000
        environment:
            - PHP_IDE_CONFIG=serverName=docker
        command: ['symfony', 'server:start', '--dir=public', '--no-tls']

    mysql:
        restart: unless-stopped
        expose:
            - 3306

    phpmyadmin:
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${PROJECT_NAME}_mysql
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        restart: unless-stopped

    node:
        command: >
            sh -c "yarn install &&
                yarn watch"

    mailer:
        container_name: ${PROJECT_NAME}_mailer
        image: mailhog/mailhog
        restart: unless-stopped
        expose:
            - 1025
        ports:
            - 8025
